# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  vsftpd:
    image: vsftpd_vsftpd
    build: .     # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    ports:
      - "192.168.20.1:20:20"
      - "192.168.20.1:21:21"
      - "192.168.20.1:10090-10100:10090-10100"
    volumes:              # Wherever your folders are
      - "/home/pi/ata-provserver-rpi/data:/home/files"
