#! /bin/sh
### BEGIN INIT INFO
# Provides:          ata-provserver
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage my cool stuff
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
workdir="/home/pi/ata-provserver-rpi"
# Everything for 'docker-compose' goes after specifying the .yml
dockercmd="docker-compose -f ${workdir}/docker-compose.yml"
startupScript="/etc/init.d/ata-provserver"

permissions(){
#    chmod +x ${workdir}/vsftpd/entrypoint.sh
    chmod +x ${workdir}/isc-dhcpd/entrypoint.sh
    chmod +x ${workdir}/lighttpd/entrypoint.sh
    chmod +x ${workdir}/isc-dhcpd/start
    chmod +x ${workdir}/lighttpd/start
    chmod -R 777 ${workdir}/data
}    

startServer(){
    permissions
    ip addr add 192.168.20.1/24 dev eth0
    sleep 2 # It takes 2 seconds for this to finalize but "ip addr" returns right away
    ${dockercmd} up -d
}

enableServer(){
    permissions
    if [ -e "${startupScript}" ]
    then
	echo "=> Re-installing as a service"
	rm -f ${startupScript}
    else
	echo "=> Installing as a service"
    fi
    ln -sf ${workdir}/ata-provserver ${startupScript}
    update-rc.d ata-provserver defaults
    docker ps
}

stopServer(){
    ${dockercmd} down
    ip addr del 192.168.20.1/24 dev eth0
}

clearLeases(){
    rm -f ${workdir}/isc-dhcpd/data/*.leases*
}    

disableServer(){
    echo "=> Removing service"
    stopServer
    update-rc.d ata-provserver remove
    rm /etc/init.d/ata-provserver
}

restartServer(){
    stopServer
    startServer
}

refreshImages(){
    stopServer                                                                           
    docker rmi -f $(docker images -a)
    startServer
}


case "$1" in
  start)
      startServer
      exit 0
      ;;
  stop)
      stopServer
      exit 0
      ;;
  restart)      
      restartServer
      exit 0
      ;;
  refresh)
      refreshImages
      exit 0
      ;;
  enable)
      enableServer
      exit 0
      ;;
  disable)
      disableServer
      exit 0
      ;;
  clearlease)
      clearLeases
      exit 0
      ;;
  *)
      echo "Usage: /etc/init.d/ata-provserver {start | stop | restart | enable | disable | clearlease}"
      exit 1
  ;;
esac
