# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  dhcpd:
    image: isc-dhcpd_dhcpd
    build: isc-dhcpd/.    # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    network_mode: "host"  # This only works with 'docker-compose'
    command: eth0         # Whatever bin or network device you want
    volumes:              # Wherever your data folder is
      - "/home/pi/ata-provserver-rpi/data:/data"

  lighttpd:
    image: lighttpd_lighttpd
    build: lighttpd/.     # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    ports:
      - "192.168.20.1:80:80"
    volumes:              # Wherever your folders are
      - "/home/pi/ata-provserver-rpi/data:/var/www/localhost/htdocs"
      - "/home/pi/ata-provserver-rpi/lighttpd/etc/lighttpd:/etc/lighttpd"

  vsftpd:
    image: vsftpd_vsftpd
    build: vsftpd/.     # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    ports:
      - "192.168.20.1:20:20"
      - "192.168.20.1:21:21"
      - "192.168.20.1:10090-10100:10090-10100"
    volumes:              # Wherever your folders are
      - "/home/pi/ata-provserver-rpi/data:/home/files"
    environment:
      - PASSWORD=files
