# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  dhcpd:
    image: isc-dhcpd_dhcpd
    build: isc-dhcpd/.    # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    network_mode: "host"  # This only works with 'docker-compose'
    command: eth0         # Whatever bin or network device you want
    privileged: true
    volumes:              # Wherever your data folder is
      - "/home/pi/ata-provserver-rpi/isc-dhcpd/data:/data"

  lighttpd:
    image: lighttpd_lighttpd
    build: lighttpd/.     # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    command: 192.168.20.1
    depends_on:
      - dhcpd
    ports:
      - "80:80"
    volumes:              # Wherever your folders are
      - "/home/pi/ata-provserver-rpi/lighttpd/www-root:/var/www/localhost/htdocs"
      - "/home/pi/ata-provserver-rpi/lighttpd/etc/lighttpd:/etc/lighttpd"
