# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  dhcpd:
    image: isc-dhcpd_dhcpd
    container_name: ata-dhcpd # This only works with 'docker-compose'
    build: isc-dhcpd/. # This only works with 'docker-compose'
    restart: always # This only works with 'docker-compose'
    network_mode: "host" # This only works with 'docker-compose'
    command: eth0 # Whatever bin or network device you want
    volumes: # Wherever your data folder is
      - "/home/pi/ata-provserver-rpi/isc-dhcpd/data:/data"

  lighttpd:
    image: lighttpd_lighttpd
    container_name: ata-lighttpd # This only works with 'docker-compose'
    build: lighttpd/. # This only works with 'docker-compose'
    restart: always # This only works with 'docker-compose'
    ports:
      - "192.168.1.1:80:80"
    volumes: # Wherever your folders are
      - "/home/pi/ata-provserver/lighttpd/www-root:/var/www/localhost/htdocs"
      - "/home/pi/ata-provserver-rpi/lighttpd/etc/lighttpd:/etc/lighttpd"
