# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  dhcpd:
    image: isc-dhcpd_dhcpd
    build: isc-dhcpd/.    # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    network_mode: "host"  # This only works with 'docker-compose'
#    command: enx0050b621aa4a         # Whatever bin or network device you want
#    command: enx00e14c6800ef         # Whatever bin or network device you want
#    command: enx00249b304a2b         # startech adapter at work
    command: eth0         # Whatever bin or network device you want    
    volumes:              # Wherever your data folder is
      - "./data:/data"

  lighttpd:
    image: lighttpd_lighttpd
    build: lighttpd/.     # This only works with 'docker-compose'
    restart: always       # This only works with 'docker-compose'
    ports:
      - "192.168.20.1:80:80"
#      - "192.168.10.1:80:80"
    volumes:              # Wherever your folders are
      - "./data:/var/www/localhost/htdocs"
      - "./lighttpd/etc/lighttpd:/etc/lighttpd"
