#! /bin/bash
# Following is here for notes

# iptables --table nat -A POSTROUTING -o ${whateverdevicehasinternet) -j MASQUERADE
# iptables --table nat -A POSTROUTING -o wlp3s0 -j MASQUERADE
# sysctl -w net.ipv4.ip_forward=1

#ip addr add 192.168.10.1/24 dev enx00e14c6800ef
#ip addr add 192.168.20.1/24 dev enx0050b621aa4a
ip addr add 192.168.20.1/24 dev eth0
#ip addr add 192.168.20.1/24 dev enx00249b304a2b # startech adapter at work
#ip addr add 192.168.10.1/24 dev enxa0cec8c66b7d
sleep 2
docker-compose up --build
