#! /bin/bash

dockerRepo="https://download.docker.com/linux/raspbian"
composeVersion="1.24.0-rc1"

# I guess the following allows installation of an https repo
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common

curl -fsSL ${dockerRepo}/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88

sudo add-apt-repository -y \
   "deb [arch=amd64] ${dockerRepo} \
   $(lsb_release -cs) \
   stable"


sudo apt update -y
sudo apt install -y docker-ce pip
sudo pip install docker-compose
