# build with:
# $ sudo docker-compose build
# start with:
# $ sudo docker-compose up
# after start, enter shell with:
# $ sudo docker exec -it lighttpddocker_lighttpd_1 ash

version: "3.7"
services:
  lighttpd:
    container_name: lighttpd-alpine
    build: .
    restart: always
    ports:
      - "192.168.20.1:80:80"
#      - "192.168.20.2:80:80"      
    volumes:
      - "../data:/var/www/localhost/htdocs"
      - "./etc/lighttpd:/etc/lighttpd"
