# build with:
# $ sudo docker-compose build
# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  dhcpd:
    container_name: dhcpd-alpine
    build: .
    network_mode: "host"
#    command: enx0050b621aa4a
#    command: enx00249b304a2b # startech adapter at work
    command: eth0    
    restart: always
    volumes:
      - "../data:/data"
