# build with:
# $ sudo docker-compose build
# start with:
# $ sudo docker-compose up

version: "3.7"
services:
  dhcpd:
    container_name: dhcpd-alpine
    build: .
    network_mode: "host"
    command: eth0
    restart: always
    privileged: true
    volumes:
      - "/home/pi/ata-provserver-rpi/isc-dhcpd/data:/data"
