#! /bin/sh
# If you want devices to connect to this device's internet connection, run:
# iptables --table nat -A POSTROUTING -o ${whateverdevicehasinternet) -j MASQUERADE
# sysctl -w net.ipv4.ip_forward=1
docker-compose -f /home/pi/ata-provserver-rpi/isc-dhcpd/docker-compose.yml up --build
